security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & (optional) read from database
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            jwt: ~
            json_login:
                check_path: /api/v1/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_dashboard
                username_parameter: email
                password_parameter: password
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_home

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api/v1/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/contact, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/vaults, roles: ROLE_USER }
        - { path: ^/passwords, roles: ROLE_USER }
        - { path: ^/alerts, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/shares, roles: ROLE_USER }
        - { path: ^/password, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
