<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20260609195115 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, username VARCHAR(255) DEFAULT NULL, encrypted_password TEXT NOT NULL, url VARCHAR(500) DEFAULT NULL, notes TEXT DEFAULT NULL, favorite BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vault_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CABD506F58AC2DF8 ON password_entry (vault_id)');
        $this->addSql('CREATE TABLE vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, archived BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF3049217E3C61F9 ON vault (owner_id)');
        $this->addSql('ALTER TABLE password_entry ADD CONSTRAINT FK_CABD506F58AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault ADD CONSTRAINT FK_FF3049217E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_entry DROP CONSTRAINT FK_CABD506F58AC2DF8');
        $this->addSql('ALTER TABLE vault DROP CONSTRAINT FK_FF3049217E3C61F9');
        $this->addSql('DROP TABLE password_entry');
        $this->addSql('DROP TABLE vault');
    }
}
