<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610084415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE password (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, encrypted_password TEXT NOT NULL, url VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vault_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35C246D558AC2DF8 ON password (vault_id)');
        $this->addSql('CREATE INDEX IDX_35C246D5A76ED395 ON password (user_id)');
        $this->addSql('CREATE TABLE vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF304921A76ED395 ON vault (user_id)');
        $this->addSql('ALTER TABLE password ADD CONSTRAINT FK_35C246D558AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password ADD CONSTRAINT FK_35C246D5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault ADD CONSTRAINT FK_FF304921A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE password DROP CONSTRAINT FK_35C246D558AC2DF8');
        $this->addSql('ALTER TABLE password DROP CONSTRAINT FK_35C246D5A76ED395');
        $this->addSql('ALTER TABLE vault DROP CONSTRAINT FK_FF304921A76ED395');
        $this->addSql('DROP TABLE password');
        $this->addSql('DROP TABLE vault');
    }
}
