<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add missing entities: Role, Permission, VaultPermission, SharedVault, Category, Tag, Notification, ActivityLog, LoginAttempt, PasswordHistory + join tables';
    }

    public function up(Schema $schema): void
    {
        // Role
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');

        // Permission
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA77153098 ON permission (code)');

        // VaultPermission
        $this->addSql('CREATE TABLE vault_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_VAULT_PERM_CODE ON vault_permission (code)');

        // SharedVault
        $this->addSql('CREATE TABLE shared_vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, accepted BOOLEAN NOT NULL DEFAULT FALSE, shared_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recipient_id INT NOT NULL, sender_id INT NOT NULL, vault_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SV_RECIPIENT ON shared_vault (recipient_id)');
        $this->addSql('CREATE INDEX IDX_SV_SENDER ON shared_vault (sender_id)');
        $this->addSql('CREATE INDEX IDX_SV_VAULT ON shared_vault (vault_id)');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_SV_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_SV_SENDER FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_SV_VAULT FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_SV_PERMISSION FOREIGN KEY (permission_id) REFERENCES vault_permission (id) NOT DEFERRABLE');

        // Category
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');

        // Tag
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');

        // Notification
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, type VARCHAR(50) NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE, is_sent BOOLEAN NOT NULL DEFAULT FALSE, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_NOTIF_USER ON notification (user_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_NOTIF_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // ActivityLog
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, ip_address VARCHAR(50) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ACTLOG_USER ON activity_log (user_id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_ACTLOG_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // LoginAttempt
        $this->addSql('CREATE TABLE login_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(50) NOT NULL, success BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_LOGIN_USER ON login_attempt (user_id)');
        $this->addSql('ALTER TABLE login_attempt ADD CONSTRAINT FK_LOGIN_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // PasswordHistory
        $this->addSql('CREATE TABLE password_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, previous_password_hash TEXT NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, password_entry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PWDHIST_ENTRY ON password_history (password_entry_id)');
        $this->addSql('ALTER TABLE password_history ADD CONSTRAINT FK_PWDHIST_ENTRY FOREIGN KEY (password_entry_id) REFERENCES password (id) NOT DEFERRABLE');

        // Join tables
        $this->addSql('CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_RP_ROLE FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_RP_PERM FOREIGN KEY (permission_id) REFERENCES permission (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE password_entry_category (password_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (password_id, category_id))');
        $this->addSql('ALTER TABLE password_entry_category ADD CONSTRAINT FK_PEC_PASSWORD FOREIGN KEY (password_id) REFERENCES password (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_entry_category ADD CONSTRAINT FK_PEC_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE password_entry_tag (password_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (password_id, tag_id))');
        $this->addSql('ALTER TABLE password_entry_tag ADD CONSTRAINT FK_PET_PASSWORD FOREIGN KEY (password_id) REFERENCES password (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_entry_tag ADD CONSTRAINT FK_PET_TAG FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE vault_tag (vault_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (vault_id, tag_id))');
        $this->addSql('ALTER TABLE vault_tag ADD CONSTRAINT FK_VT_VAULT FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault_tag ADD CONSTRAINT FK_VT_TAG FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE');

        // Seed VaultPermission data
        $this->addSql("INSERT INTO vault_permission (code, name, description) VALUES ('READ', 'Lecture', 'Consultation uniquement')");
        $this->addSql("INSERT INTO vault_permission (code, name, description) VALUES ('WRITE', 'Écriture', 'Lecture et modification')");
        $this->addSql("INSERT INTO vault_permission (code, name, description) VALUES ('ADMIN', 'Administration', 'Accès complet')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE vault_tag');
        $this->addSql('DROP TABLE password_entry_tag');
        $this->addSql('DROP TABLE password_entry_category');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE password_history');
        $this->addSql('DROP TABLE login_attempt');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE shared_vault');
        $this->addSql('DROP TABLE vault_permission');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE role');
    }
}
