<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706204137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, ip_address VARCHAR(50) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647A76ED395 ON activity_log (user_id)');
        $this->addSql('CREATE TABLE base_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, discr VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, message TEXT DEFAULT NULL, is_sent BOOLEAN DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C3B2912A76ED395 ON base_notification (user_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contact_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE login_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(50) NOT NULL, success BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C11C1BA76ED395 ON login_attempt (user_id)');
        $this->addSql('CREATE TABLE password_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, username VARCHAR(255) DEFAULT NULL, encrypted_password TEXT NOT NULL, url VARCHAR(500) DEFAULT NULL, notes TEXT DEFAULT NULL, favorite BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vault_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CABD506F58AC2DF8 ON password_entry (vault_id)');
        $this->addSql('CREATE INDEX IDX_CABD506FA76ED395 ON password_entry (user_id)');
        $this->addSql('CREATE TABLE password_entry_category (password_entry_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (password_entry_id, category_id))');
        $this->addSql('CREATE INDEX IDX_FA1F2A02AA1DB82 ON password_entry_category (password_entry_id)');
        $this->addSql('CREATE INDEX IDX_FA1F2A012469DE2 ON password_entry_category (category_id)');
        $this->addSql('CREATE TABLE password_entry_tag (password_entry_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (password_entry_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_6BC19CC72AA1DB82 ON password_entry_tag (password_entry_id)');
        $this->addSql('CREATE INDEX IDX_6BC19CC7BAD26311 ON password_entry_tag (tag_id)');
        $this->addSql('CREATE TABLE password_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, previous_password_hash TEXT NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, password_entry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3521442AA1DB82 ON password_history (password_entry_id)');
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA77153098 ON permission (code)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_6F7DF886D60322AC ON role_permission (role_id)');
        $this->addSql('CREATE INDEX IDX_6F7DF886FED90CCA ON role_permission (permission_id)');
        $this->addSql('CREATE TABLE shared_vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, accepted BOOLEAN NOT NULL, shared_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recipient_id INT NOT NULL, sender_id INT NOT NULL, vault_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15EA43CE92F8F78 ON shared_vault (recipient_id)');
        $this->addSql('CREATE INDEX IDX_15EA43CF624B39D ON shared_vault (sender_id)');
        $this->addSql('CREATE INDEX IDX_15EA43C58AC2DF8 ON shared_vault (vault_id)');
        $this->addSql('CREATE INDEX IDX_15EA43CFED90CCA ON shared_vault (permission_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, email_verified BOOLEAN NOT NULL, profile_image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is2fa_enabled BOOLEAN NOT NULL, two_factor_secret VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976F5C865 ON "user" (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3A76ED395 ON user_role (user_id)');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3D60322AC ON user_role (role_id)');
        $this->addSql('CREATE TABLE user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(45) NOT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, location VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8849CBDEA76ED395 ON user_session (user_id)');
        $this->addSql('CREATE TABLE vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, archived BOOLEAN NOT NULL, encrypted_key TEXT DEFAULT NULL, key_encryption_version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF304921A76ED395 ON vault (user_id)');
        $this->addSql('CREATE TABLE vault_tag (vault_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (vault_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_DB63091358AC2DF8 ON vault_tag (vault_id)');
        $this->addSql('CREATE INDEX IDX_DB630913BAD26311 ON vault_tag (tag_id)');
        $this->addSql('CREATE TABLE vault_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AEC5D89B77153098 ON vault_permission (code)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE base_notification ADD CONSTRAINT FK_C3B2912A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE login_attempt ADD CONSTRAINT FK_8C11C1BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_entry ADD CONSTRAINT FK_CABD506F58AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_entry ADD CONSTRAINT FK_CABD506FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_entry_category ADD CONSTRAINT FK_FA1F2A02AA1DB82 FOREIGN KEY (password_entry_id) REFERENCES password_entry (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_entry_category ADD CONSTRAINT FK_FA1F2A012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_entry_tag ADD CONSTRAINT FK_6BC19CC72AA1DB82 FOREIGN KEY (password_entry_id) REFERENCES password_entry (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_entry_tag ADD CONSTRAINT FK_6BC19CC7BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_history ADD CONSTRAINT FK_F3521442AA1DB82 FOREIGN KEY (password_entry_id) REFERENCES password_entry (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_15EA43CE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_15EA43CF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_15EA43C58AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared_vault ADD CONSTRAINT FK_15EA43CFED90CCA FOREIGN KEY (permission_id) REFERENCES vault_permission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_8849CBDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault ADD CONSTRAINT FK_FF304921A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault_tag ADD CONSTRAINT FK_DB63091358AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vault_tag ADD CONSTRAINT FK_DB630913BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647A76ED395');
        $this->addSql('ALTER TABLE base_notification DROP CONSTRAINT FK_C3B2912A76ED395');
        $this->addSql('ALTER TABLE login_attempt DROP CONSTRAINT FK_8C11C1BA76ED395');
        $this->addSql('ALTER TABLE password_entry DROP CONSTRAINT FK_CABD506F58AC2DF8');
        $this->addSql('ALTER TABLE password_entry DROP CONSTRAINT FK_CABD506FA76ED395');
        $this->addSql('ALTER TABLE password_entry_category DROP CONSTRAINT FK_FA1F2A02AA1DB82');
        $this->addSql('ALTER TABLE password_entry_category DROP CONSTRAINT FK_FA1F2A012469DE2');
        $this->addSql('ALTER TABLE password_entry_tag DROP CONSTRAINT FK_6BC19CC72AA1DB82');
        $this->addSql('ALTER TABLE password_entry_tag DROP CONSTRAINT FK_6BC19CC7BAD26311');
        $this->addSql('ALTER TABLE password_history DROP CONSTRAINT FK_F3521442AA1DB82');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE shared_vault DROP CONSTRAINT FK_15EA43CE92F8F78');
        $this->addSql('ALTER TABLE shared_vault DROP CONSTRAINT FK_15EA43CF624B39D');
        $this->addSql('ALTER TABLE shared_vault DROP CONSTRAINT FK_15EA43C58AC2DF8');
        $this->addSql('ALTER TABLE shared_vault DROP CONSTRAINT FK_15EA43CFED90CCA');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3A76ED395');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3D60322AC');
        $this->addSql('ALTER TABLE user_session DROP CONSTRAINT FK_8849CBDEA76ED395');
        $this->addSql('ALTER TABLE vault DROP CONSTRAINT FK_FF304921A76ED395');
        $this->addSql('ALTER TABLE vault_tag DROP CONSTRAINT FK_DB63091358AC2DF8');
        $this->addSql('ALTER TABLE vault_tag DROP CONSTRAINT FK_DB630913BAD26311');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE base_notification');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE login_attempt');
        $this->addSql('DROP TABLE password_entry');
        $this->addSql('DROP TABLE password_entry_category');
        $this->addSql('DROP TABLE password_entry_tag');
        $this->addSql('DROP TABLE password_history');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE shared_vault');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE user_session');
        $this->addSql('DROP TABLE vault');
        $this->addSql('DROP TABLE vault_tag');
        $this->addSql('DROP TABLE vault_permission');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
